import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { AppNavBar } from "@/components/app-nav-bar";
import { AppMenu } from "@/components/app-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const navbarHeight = 16 * 4;

  return (
    <html lang="en">
        <body className={`${inter.className}`}>
          <Providers>
          <div className="flex flex-col h-screen">
            <AppNavBar></AppNavBar>

            <div className="flex" style={{ height: `calc(100vh - ${navbarHeight}px)` }}>
              <div className="flex-none overflow-y-scroll bg-white bg-opacity-75">
                <AppMenu></AppMenu>
              </div>
              <div className="flex-auto">
                {children}
              </div>
            </div>
          </div>
          </Providers>
        </body>
    </html>
  );
}
